sudo: false
language: python
python:
  - 3.6

install:
  - pip install -U pip wheel setuptools python-coveralls tox tox-travis

script:
  - pytest

services:
  - rabbitmq

addons:
  apt_packages:
    - pandoc

after_success:
  - coveralls